name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: ap-northeast-2
      ECR_REGISTRY: 809093418282.dkr.ecr.ap-northeast-2.amazonaws.com
      ECR_REPO: your-repository-name

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile ecr-user
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile ecr-user
        aws configure set region ${AWS_DEFAULT_REGION} --profile ecr-user
        aws ecr get-login-password --region ${AWS_DEFAULT_REGION} --profile ecr-user | docker login --username AWS --password-stdin ${ECR_REGISTRY}

    - name: Build and push Docker image to ECR
      run: |
        docker build -t ${ECR_REPO} .
        docker tag ${ECR_REPO}:latest ${ECR_REGISTRY}/${ECR_REPO}:latest
        docker push ${ECR_REGISTRY}/${ECR_REPO}:latest
